[package]
name = "rssreader"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.10", features = ["tokio", "image"] }
rss = "2.0"
reqwest = {version = "0.11", features = ["blocking"]}